/**************************************************************************************
* Generated by Eds2Od from PressureSensor.eds
* Do not edit this file manually - regenerate it from the EDS source instead.
**************************************************************************************/
#include "PressureSensorOd.hpp"


using namespace CANoopEn;


/* ---------------------------------------------------------------------------------
 Description    : Constructor

 Parameters     : - listener            Listener to be notified about value changes
                  - nodeId              Node id

 Return values  : -
 ----------------------------------------------------------------------------------- */
PressureSensorOd::PressureSensorOd(ICoObjectDictionaryListener& listener, uint16_t nodeId) :
    CoObjectDictionary(listener),
    // *** BEGIN GENERATED CODE (Eds2Od) *******************************************
    _entryDeviceType(CANoopEn::CoOdEntryUnsigned32(0x1000, 0x00, 0x00020194, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryErrorRegister(CANoopEn::CoOdEntryUnsigned8(0x1001, 0x00, 0x00, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryManufacturerDeviceName(CANoopEn::CoOdEntryVisibleString(0x1008, 0x00, _entryManufacturerDeviceNameBuffer, sizeof(_entryManufacturerDeviceNameBuffer), CANoopEn::CoOdAccessType::Const)),
    _entryManufacturerHardwareVersion(CANoopEn::CoOdEntryVisibleString(0x1009, 0x00, _entryManufacturerHardwareVersionBuffer, sizeof(_entryManufacturerHardwareVersionBuffer), CANoopEn::CoOdAccessType::Const)),
    _entryManufacturerSoftwareVersion(CANoopEn::CoOdEntryVisibleString(0x100A, 0x00, _entryManufacturerSoftwareVersionBuffer, sizeof(_entryManufacturerSoftwareVersionBuffer), CANoopEn::CoOdAccessType::Const)),
    _entryProducerHeartbeatTime(CANoopEn::CoOdEntryUnsigned16(0x1017, 0x00, 1000, CANoopEn::CoOdAccessType::ReadWrite)),
    _entryIdentityObjectNumberOfEntries(CANoopEn::CoOdEntryUnsigned8(0x1018, 0x00, 4, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryIdentityObjectVendorID(CANoopEn::CoOdEntryUnsigned32(0x1018, 0x01, 0x00000000, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryIdentityObjectProductCode(CANoopEn::CoOdEntryUnsigned32(0x1018, 0x02, 0x00000001, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryIdentityObjectRevisionNumber(CANoopEn::CoOdEntryUnsigned32(0x1018, 0x03, 0x00010000, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryIdentityObjectSerialNumber(CANoopEn::CoOdEntryUnsigned32(0x1018, 0x04, 0x00000001, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryServerSDOParameterNumberOfEntries(CANoopEn::CoOdEntryUnsigned8(0x1200, 0x00, 2, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryServerSDOParameterCOBIDClientToServer(CANoopEn::CoOdEntryUnsigned32(0x1200, 0x01, nodeId + 0x600, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryServerSDOParameterCOBIDServerToClient(CANoopEn::CoOdEntryUnsigned32(0x1200, 0x02, nodeId + 0x580, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryTPDO1CommunicationParameterNumberOfEntries(CANoopEn::CoOdEntryUnsigned8(0x1800, 0x00, 2, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryTPDO1CommunicationParameterCOBIDUsedByTPDO1(CANoopEn::CoOdEntryUnsigned32(0x1800, 0x01, nodeId + 0x180, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryTPDO1CommunicationParameterTransmissionType(CANoopEn::CoOdEntryUnsigned8(0x1800, 0x02, 255, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryTPDO1MappingParameterNumberOfMappedObjects(CANoopEn::CoOdEntryUnsigned8(0x1A00, 0x00, 2, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryTPDO1MappingParameterPressureMapping(CANoopEn::CoOdEntryUnsigned32(0x1A00, 0x01, 0x91300120, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryTPDO1MappingParameterDepthMapping(CANoopEn::CoOdEntryUnsigned32(0x1A00, 0x02, 0x20000020, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryDepthMillimeters(CANoopEn::CoOdEntryUnsigned32(0x2000, 0x00, 0, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryAISensorTypeNumberOfEntries(CANoopEn::CoOdEntryUnsigned8(0x6110, 0x00, 1, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryAISensorTypePressureTransducer(CANoopEn::CoOdEntryUnsigned16(0x6110, 0x01, 90, CANoopEn::CoOdAccessType::Const)),
    _entryAIPhysicalUnitPVNumberOfEntries(CANoopEn::CoOdEntryUnsigned8(0x6131, 0x00, 1, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryAIPhysicalUnitPVPressureUnitPascal(CANoopEn::CoOdEntryUnsigned32(0x6131, 0x01, 0x00220000, CANoopEn::CoOdAccessType::Const)),
    _entryAIDecimalDigitsPVNumberOfEntries(CANoopEn::CoOdEntryUnsigned8(0x6132, 0x00, 1, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryAIDecimalDigitsPVPressureDecimalDigits(CANoopEn::CoOdEntryUnsigned8(0x6132, 0x01, 0, CANoopEn::CoOdAccessType::Const)),
    _entryAIStatusNumberOfEntries(CANoopEn::CoOdEntryUnsigned8(0x6150, 0x00, 1, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryAIStatusPressureStatus(CANoopEn::CoOdEntryUnsigned8(0x6150, 0x01, 0, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryAIInputFVInteger32NumberOfEntries(CANoopEn::CoOdEntryUnsigned8(0x9100, 0x00, 1, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryAIInputFVInteger32PressureRawADCValue(CANoopEn::CoOdEntryInteger32(0x9100, 0x01, 0, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryAIInputPVInteger32NumberOfEntries(CANoopEn::CoOdEntryUnsigned8(0x9130, 0x00, 1, CANoopEn::CoOdAccessType::ReadOnly)),
    _entryAIInputPVInteger32PressurePascals(CANoopEn::CoOdEntryInteger32(0x9130, 0x01, 0, CANoopEn::CoOdAccessType::ReadOnly)),
    _tpdoMappingParameter1(CANoopEn::CoOdPdoMappingParameter(1))
    // *** END GENERATED CODE ******************************************************
{
    // *** BEGIN GENERATED CODE (Eds2Od) *******************************************
    AddEntry(_entryDeviceType);
    AddEntry(_entryErrorRegister);
    AddEntry(_entryManufacturerDeviceName);
    AddEntry(_entryManufacturerHardwareVersion);
    AddEntry(_entryManufacturerSoftwareVersion);
    AddEntry(_entryProducerHeartbeatTime);
    AddEntry(_entryIdentityObjectNumberOfEntries);
    AddEntry(_entryIdentityObjectVendorID);
    AddEntry(_entryIdentityObjectProductCode);
    AddEntry(_entryIdentityObjectRevisionNumber);
    AddEntry(_entryIdentityObjectSerialNumber);
    AddEntry(_entryServerSDOParameterNumberOfEntries);
    AddEntry(_entryServerSDOParameterCOBIDClientToServer);
    AddEntry(_entryServerSDOParameterCOBIDServerToClient);
    AddEntry(_entryTPDO1CommunicationParameterNumberOfEntries);
    AddEntry(_entryTPDO1CommunicationParameterCOBIDUsedByTPDO1);
    AddEntry(_entryTPDO1CommunicationParameterTransmissionType);
    AddEntry(_entryTPDO1MappingParameterNumberOfMappedObjects);
    AddEntry(_entryTPDO1MappingParameterPressureMapping);
    AddEntry(_entryTPDO1MappingParameterDepthMapping);
    AddEntry(_entryDepthMillimeters);
    AddEntry(_entryAISensorTypeNumberOfEntries);
    AddEntry(_entryAISensorTypePressureTransducer);
    AddEntry(_entryAIPhysicalUnitPVNumberOfEntries);
    AddEntry(_entryAIPhysicalUnitPVPressureUnitPascal);
    AddEntry(_entryAIDecimalDigitsPVNumberOfEntries);
    AddEntry(_entryAIDecimalDigitsPVPressureDecimalDigits);
    AddEntry(_entryAIStatusNumberOfEntries);
    AddEntry(_entryAIStatusPressureStatus);
    AddEntry(_entryAIInputFVInteger32NumberOfEntries);
    AddEntry(_entryAIInputFVInteger32PressureRawADCValue);
    AddEntry(_entryAIInputPVInteger32NumberOfEntries);
    AddEntry(_entryAIInputPVInteger32PressurePascals);

    AddTpdoMappingParameter(_tpdoMappingParameter1);
    _tpdoMappingParameter1.AddMappingParameterEntry(_entryTPDO1MappingParameterPressureMapping);
    _tpdoMappingParameter1.AddMappingParameterEntry(_entryTPDO1MappingParameterDepthMapping);
    // *** END GENERATED CODE ******************************************************

    // Eds2Od deliberately leaves VISIBLE_STRING buffers empty.  Initializing
    // them outside the generated markers keeps regeneration idempotent.
    SetValue(0x1008, 0x00, "SAUVC Pressure Sensor");
    SetValue(0x1009, 0x00, "1.0");
    SetValue(0x100A, 0x00, "1.0.0");
}
