/**************************************************************************************
* Generated by Eds2Od from PressureSensor.eds
* Do not edit this file manually - regenerate it from the EDS source instead.
**************************************************************************************/
#ifndef _PRESSURE_SENSOR_OD_HPP
#define _PRESSURE_SENSOR_OD_HPP


#include "CoObjectDictionary.hpp"


namespace CANoopEn
{

class PressureSensorOd : public CoObjectDictionary
{
public:

/* ---------------------------------------------------------------------------------
 Description    : Constructor

 Parameters     : - listener            Listener to be notified about value changes
                  - nodeId              Node id

 Return values  : -
 ----------------------------------------------------------------------------------- */
PressureSensorOd(ICoObjectDictionaryListener& listener, uint16_t nodeId);


private:

// *** BEGIN GENERATED CODE (Eds2Od) ***********************************************
static constexpr size_t NumberOfOdEntries = 33;
static_assert(NumberOfOdEntries <= CANoopEn::CoSettings::MaxNumberOfOdEntries,
              "CoSettings::MaxNumberOfOdEntries is too small for this object dictionary");

CANoopEn::CoOdEntryUnsigned32 _entryDeviceType;
CANoopEn::CoOdEntryUnsigned8 _entryErrorRegister;
char _entryManufacturerDeviceNameBuffer[128];
CANoopEn::CoOdEntryVisibleString _entryManufacturerDeviceName;
char _entryManufacturerHardwareVersionBuffer[128];
CANoopEn::CoOdEntryVisibleString _entryManufacturerHardwareVersion;
char _entryManufacturerSoftwareVersionBuffer[128];
CANoopEn::CoOdEntryVisibleString _entryManufacturerSoftwareVersion;
CANoopEn::CoOdEntryUnsigned16 _entryProducerHeartbeatTime;
CANoopEn::CoOdEntryUnsigned8 _entryIdentityObjectNumberOfEntries;
CANoopEn::CoOdEntryUnsigned32 _entryIdentityObjectVendorID;
CANoopEn::CoOdEntryUnsigned32 _entryIdentityObjectProductCode;
CANoopEn::CoOdEntryUnsigned32 _entryIdentityObjectRevisionNumber;
CANoopEn::CoOdEntryUnsigned32 _entryIdentityObjectSerialNumber;
CANoopEn::CoOdEntryUnsigned8 _entryServerSDOParameterNumberOfEntries;
CANoopEn::CoOdEntryUnsigned32 _entryServerSDOParameterCOBIDClientToServer;
CANoopEn::CoOdEntryUnsigned32 _entryServerSDOParameterCOBIDServerToClient;
CANoopEn::CoOdEntryUnsigned8 _entryTPDO1CommunicationParameterNumberOfEntries;
CANoopEn::CoOdEntryUnsigned32 _entryTPDO1CommunicationParameterCOBIDUsedByTPDO1;
CANoopEn::CoOdEntryUnsigned8 _entryTPDO1CommunicationParameterTransmissionType;
CANoopEn::CoOdEntryUnsigned8 _entryTPDO1MappingParameterNumberOfMappedObjects;
CANoopEn::CoOdEntryUnsigned32 _entryTPDO1MappingParameterPressureMapping;
CANoopEn::CoOdEntryUnsigned32 _entryTPDO1MappingParameterDepthMapping;
CANoopEn::CoOdEntryUnsigned32 _entryDepthMillimeters;
CANoopEn::CoOdEntryUnsigned8 _entryAISensorTypeNumberOfEntries;
CANoopEn::CoOdEntryUnsigned16 _entryAISensorTypePressureTransducer;
CANoopEn::CoOdEntryUnsigned8 _entryAIPhysicalUnitPVNumberOfEntries;
CANoopEn::CoOdEntryUnsigned32 _entryAIPhysicalUnitPVPressureUnitPascal;
CANoopEn::CoOdEntryUnsigned8 _entryAIDecimalDigitsPVNumberOfEntries;
CANoopEn::CoOdEntryUnsigned8 _entryAIDecimalDigitsPVPressureDecimalDigits;
CANoopEn::CoOdEntryUnsigned8 _entryAIStatusNumberOfEntries;
CANoopEn::CoOdEntryUnsigned8 _entryAIStatusPressureStatus;
CANoopEn::CoOdEntryUnsigned8 _entryAIInputFVInteger32NumberOfEntries;
CANoopEn::CoOdEntryInteger32 _entryAIInputFVInteger32PressureRawADCValue;
CANoopEn::CoOdEntryUnsigned8 _entryAIInputPVInteger32NumberOfEntries;
CANoopEn::CoOdEntryInteger32 _entryAIInputPVInteger32PressurePascals;
CANoopEn::CoOdPdoMappingParameter _tpdoMappingParameter1;
// *** END GENERATED CODE **********************************************************

};

} // namespace CANoopEn

#endif
